name: Build gpt.c

on:
  create:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  build-cpu:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init submodules
        run: |
          git submodule update --init --recursive

      - name: Install Dependencies
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y libomp-dev build-essential gcc gfortran make
          elif [ "${{ runner.os }}" == "macOS" ]; then
            brew install libomp && brew install argp-standalone
          fi

      - name: Compile third party libraries
        run: |
          make third_party

      - name: Compile gpt.c
        run: | 
          make